# Generated by Django 5.1.6 on 2025-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom Employe')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom Employe')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse Employe')),
                ('fonction', models.CharField(max_length=255, verbose_name='Fonction Employe')),
                ('contrat', models.CharField(max_length=25, verbose_name='Contrat Employe')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Employe')),
            ],
        ),
    ]
