# Generated by Django 5.1.6 on 2025-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employes',
            name='contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employes',
            name='fonction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employes',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employes',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
